name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      WASMINNA_PATH: wasminna
      WASM_SPEC_PATH: spec
    steps:
    - uses: actions/checkout@v3
      with:
        path: ${{ env.WASMINNA_PATH }}
    - uses: actions/checkout@v3
      with:
        repository: WebAssembly/spec
        path: ${{ env.WASM_SPEC_PATH }}
    - uses: ruby/setup-ruby@v1
      with:
        working-directory: ${{ env.WASMINNA_PATH }}
    - run: |
        "$WASMINNA_PATH"/test.sh
