name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      WASM_SPEC_PATH: spec
    steps:
    - uses: actions/checkout@v3
      with:
        path: wasminna
    - uses: actions/checkout@v3
      with:
        repository: WebAssembly/spec
        path: ${{ env.WASM_SPEC_PATH }}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
    - run: wasminna/test.sh
